version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      testcontainers-go:
        patterns:
          - github.com/testcontainers/testcontainers-go
          - github.com/testcontainers/testcontainers-go/modules/*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
