// Command generate-render-samples renders internal/render.Samples and
// writes the PNG gallery under docs/images/render-samples/ plus the
// docs/render-samples.md gallery page that displays them. The same sample
// list backs internal/render's TestRenderSamplesMatchCheckedInGallery
// regression test, so re-run this command and review the resulting diff
// whenever a rendering change is intentional.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/davidvanlaatum/inventree-mcp/internal/render"
)

var familyLabels = map[render.Family]string{
	render.FamilyResistor:  "Resistors",
	render.FamilyDiode:     "Diodes",
	render.FamilyLED:       "LEDs",
	render.FamilyCapacitor: "Capacitors",
	render.FamilyFuse:      "Fuses",
}

// familyOrder is fixed and matches the order families first appear in
// render.Samples, so the gallery's section order doesn't depend on map
// iteration.
var familyOrder = []render.Family{
	render.FamilyResistor,
	render.FamilyDiode,
	render.FamilyLED,
	render.FamilyCapacitor,
	render.FamilyFuse,
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "generate-render-samples:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findModuleRoot()
	if err != nil {
		return err
	}
	imagesDir := filepath.Join(root, "docs", "images", "render-samples")
	if err := os.MkdirAll(imagesDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", imagesDir, err)
	}

	byFamily := map[render.Family][]render.Sample{}
	for _, s := range render.Samples {
		result, err := s.Render()
		if err != nil {
			return fmt.Errorf("render sample %s: %w", s.Name, err)
		}
		path := filepath.Join(imagesDir, s.Name+".png")
		if err := os.WriteFile(path, result.PNG, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		byFamily[s.Family] = append(byFamily[s.Family], s)
	}

	var b strings.Builder
	b.WriteString("# Component Image Gallery\n\n")
	b.WriteString("Example `render_component_image` output for every supported family (F-S90). ")
	b.WriteString("Generated by `cmd/generate-render-samples` from `internal/render.Samples`; ")
	b.WriteString("the same list backs `TestRenderSamplesMatchCheckedInGallery`, so these images are checked ")
	b.WriteString("byte-for-byte against what the renderer actually produces, not just illustrative screenshots. ")
	b.WriteString("Regenerate with `go generate ./internal/render/...` after a rendering change and review the diff before committing.\n")

	for _, family := range familyOrder {
		samples := byFamily[family]
		if len(samples) == 0 {
			continue
		}
		b.WriteString("## " + familyLabels[family] + "\n\n")
		for _, s := range samples {
			b.WriteString("### " + s.Name + "\n\n")
			b.WriteString(s.Description + "\n\n")
			b.WriteString("![" + s.Name + "](images/render-samples/" + s.Name + ".png)\n\n")
		}
	}

	mdPath := filepath.Join(root, "docs", "render-samples.md")
	if err := os.WriteFile(mdPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", mdPath, err)
	}
	return nil
}

// findModuleRoot walks up from the working directory to find the directory
// containing go.mod, so this command produces the same output whether it's
// invoked via `go generate` (which runs with the source file's directory as
// the working directory) or directly from the repository root.
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found above %s", dir)
		}
		dir = parent
	}
}
