name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

env:
  GOFLAGS: -trimpath

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        go-version: [ '1.25', 'stable' ]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 10

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - uses: gwatts/go-coverage-action@v2
        id: coverage
        with:
          coverage-threshold: 80
          cover-pkg: ./...
          notes-ref: gocoverage-${{ matrix.go-version }}

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

  gremlins:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - uses: go-gremlins/gremlins-action@v1
        with:
          version: latest
