name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

env:
  GOFLAGS: -trimpath
  GREMLINS_VERSION: v0.6.0

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 10

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - uses: gwatts/go-coverage-action@v2
        id: coverage
        with:
          coverage-threshold: 80
          cover-mode: atomic
          cover-pkg: ./...
          test-args: '["-v", "-race"]'
          notes-ref: gocoverage-stable

      - name: Update coverage badge
        uses: schneegans/dynamic-badges-action@v1.8.0
        if: github.ref_name == 'main'
        with:
          auth: ${{ secrets.COVERAGE_GIST_SECRET }}
          gistID: 709e99cf973e064f68cf3937b3d5c633
          filename: coverage.json
          label: Go Coverage
          message: ${{ steps.coverage.outputs.coverage-pct-1dp }}%
          color: ${{ steps.coverage.outputs.meets-threshold == 'true' && 'green' || 'red' }}

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

  gremlins:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - name: Cache Gremlins binary
        uses: actions/cache@v6
        with:
          path: ${{ runner.tool_cache }}/gremlins
          key: ${{ runner.os }}-${{ runner.arch }}-gremlins-${{ env.GREMLINS_VERSION }}
      - uses: go-gremlins/gremlins-action@v1
        with:
          version: ${{ env.GREMLINS_VERSION }}
